optim: adam
init: xavier_uniform
max_epoch: 1
batch_type: folded
batch_size: 6 # batch_size 16 can be trained on 4 RTX 2080ti
iterator_type: chunk
chunk_length: 24000
num_workers: 4
optim_conf:
    lr: 0.00015
    weight_decay: 0
patience: 5
val_scheduler_criterion:
- valid
- loss
best_model_criterion:
-   - valid
    - si_snr
    - max
-   - valid
    - loss
    - min
keep_nbest_models: 1
scheduler: reducelronplateau
scheduler_conf:
    mode: min
    factor: 0.5
    patience: 1
model_conf:
    loss_type: si_snr
encoder: codec
encoder_conf:
    channel: 512
    codec_choice: "ESPnet"
    codec_fs: 16000 #must match the codec
    sample_fs: 8000
    device: "cuda:0"
    dump_audio: True
    checkpoint_path: "/ocean/projects/cis210027p/masuyama/espnet-codec/pretrained-codec/16khz_soundstream/train.total_count.best.pth"
    config_path: "/ocean/projects/cis210027p/masuyama/espnet-codec/pretrained-codec/16khz_soundstream/config.yaml"
decoder: codec
decoder_conf:
    channel: 512
    codec_choice: "ESPnet"
    codec_fs: 16000 #must match the codec
    sample_fs: 8000
    device: "cuda:0"
    dump_audio: True
    checkpoint_path: "/ocean/projects/cis210027p/masuyama/espnet-codec/pretrained-codec/16khz_soundstream/train.total_count.best.pth"
    config_path: "/ocean/projects/cis210027p/masuyama/espnet-codec/pretrained-codec/16khz_soundstream/config.yaml"
separator: codec
separator_conf:
    internal_dim: 512
    num_spk: 2
    trf_num_layers: 8
    predict_noise: False