corelm: ar_delay
corelm_conf:
    share_emb: false
    qk_norm: true
    att_unit: 768
    head: 12
    layer: 12

# Dataloader
batch_type: numel
batch_bins: 8000
# batch_type: folded
# batch_size: 8
accum_grad: 1
grad_clip: 5
max_epoch: 60
num_workers: 8
drop_last_iter: true
log_interval: 1000
num_att_plot: 0

# Criterion & Optimization
optim: adamw
optim_conf:
    lr: 0.001
    betas:
        - 0.9
        - 0.95
scheduler: warmuplr
scheduler_conf:
    warmup_steps: 70000

best_model_criterion:
-   - valid
    - acc
    - max
-   - valid
    - total_count
    - max
keep_nbest_models: 5
nbest_averaging_interval: 5


# Global settings
use_amp: true
use_tf32: false
use_fsdp: false
encoder_decoder_format: false
codec_token_per_frame: 8 # encodec
codec_token_in_use: 8
speaker_prompt_length: 500 # 50fps, a.k.a., 10s