corelm: valle
corelm_conf:
    share_emb: false
    att_unit: 512
    head: 8
    ar_layer: 12
    nar_layer: 12

# Dataloader
batch_type: numel
batch_bins: 16000
accum_grad: 2
grad_clip: 5
max_epoch: 50
num_workers: 4
log_interval: 500
num_att_plot: 0

# Criterion & Optimization
optim: adamw
optim_conf:
    lr: 0.002
    betas:
        - 0.9
        - 0.95
scheduler: warmuplr
scheduler_conf:
    warmup_steps: 10000

best_model_criterion:
-   - valid
    - acc
    - max
-   - valid
    - total_count
    - max
keep_nbest_models: 10
nbest_averaging_interval: 10


# Global settings
use_amp: true
use_tf32: false
encoder_decoder_format: false
codec_token_per_frame: 8
codec_token_in_use: 8
