optim: adam
init: xavier_uniform
max_epoch: 100
batch_type: folded
batch_size:  128
num_workers: 4
optim_conf:
    lr: 1.0e-03
    eps: 1.0e-08
    weight_decay: 1.0e-7
patience: 10
unused_parameters: true
val_scheduler_criterion:
- valid
- loss
best_model_criterion:
-   - valid
    - si_snr
    - max
-   - valid
    - loss
    - min
keep_nbest_models: 1
scheduler: reducelronplateau
scheduler_conf:
    mode: min
    factor: 0.7
    patience: 1
model_conf:
    loss_type: encoder_mse
    mask_type: irm
encoder: s3prl
encoder_conf:
    upstream_conf:
        upstream: hubert_large_ll60k  # Note: If the upstream is changed, please change the input_size in the preencoder.
    download_dir: ./hub
    multilayer_feature: False
decoder: same
separator: rnn
separator_conf:
    rnn_type: blstm
    num_spk: 2
    nonlinear: relu
    layer: 4
    unit: 512
    dropout: 0.5
